POST http://localhost:5000/templates
content-type: application/json

{
    "entry": "Test2"
}

###

DELETE http://localhost:5000/templates/6259e5c8da98467f2465b2a4
content-type: application/json


###